version: '3.9'

services:
  web:
    build: .
    container_name: note-app
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./api:/var/www/html/api
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
    networks:
        - networkProjet

  db:
    image: mysql:8.0
    container_name: notes_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/notes.sql:/docker-entrypoint-initdb.d/notes.sql
    networks:
        - networkProjet

networks:
  networkProjet:
    driver: bridge

volumes:
  db_data:
