version: '3.9'

services:
  web:
    build: .
    container_name: note-app
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
#      - ./api:/var/www/html/api
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: notes_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${root}
      MYSQL_USER: ${user}
      MYSQL_PASSWORD: ${password}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/notes.sql:/docker-entrypoint-initdb.d/notes.sql

volumes:
  db_data:
