name: Run Tests

on:
  pull_request:
    branches:
      - '**'
    branches-ignore:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (ou autre environnement selon vos tests)
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Adaptez cette commande en fonction de vos tests
